name: "Process Latest Release with 7200 seconds"

on:
  workflow_dispatch: # Allow manual triggering with input
    inputs:
      model_build_time:
        description: "Override model build time in seconds (e.g. '7200')"
        required: false
        default: "7200"

env:
  MODEL_BUILD_SECONDS: "7200"

jobs:
  process-latest-release:
    name: "Process Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      # Step 1: Checkout repository
      - name: "Checkout Code"
        uses: actions/checkout@v4

      # Step 2: Execute the script to process the release
      - name: Execute
        run: |
          chmod +x ./get_latest_release.sh
          ./get_latest_release.sh
        shell: bash

      # # Step 3: Setup .NET
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 8.0.x

      # # Step 4: Install ML.NET CLI
      # - name: Install ML.NET CLI
      #   run: dotnet tool install -g mlnet-linux-x64

      # # Step 6: Train the model with matrix train time
      # - name: Train your model
      #   run: mlnet classification --dataset "processed/combined_refactored.txt" --label-col 1 --has-header false --name "SentimentModel_${{ github.event.inputs.model_build_time || env.MODEL_BUILD_SECONDS }}" --train-time ${{ github.event.inputs.model_build_time || env.MODEL_BUILD_SECONDS }}

      - name: Configure Git
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
    
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        run: |
          git add .
          git commit -m "Automated update" || echo "No changes to commit"
          git push || echo "No changes to push"